# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Pairwise squared distances between two point sets (rows)
#' @param A nxd
#' @param B mxd
#' @return nxm matrix of ||a_i - b_j||^2
pairwise_sqdist_cpp <- function(A, B) {
    .Call(`_dkge_pairwise_sqdist_cpp`, A, B)
}

sinkhorn_plan_cpp <- function(C, mu, nu, epsilon, max_iter, tol, log_u_init = NULL, log_v_init = NULL, keep_duals = TRUE) {
    .Call(`_dkge_sinkhorn_plan_cpp`, C, mu, nu, epsilon, max_iter, tol, log_u_init, log_v_init, keep_duals)
}

